#!/usr/bin/env python3
"""Generate src/bombs.c from the packed Atari "Bomb Squad" bomb table.

The original game packs its 48 bombs into one string, two characters per
wire: a letter 'a'..'f' for the wire colour and a digit '0'..'5' for the cut
order (0 = never cut this wire). Bombs come in order: 12 with 3 wires, 12
with 4, 12 with 5, 12 with 6.

Run this script and redirect stdout to src/bombs.c:

    python3 tools/gen_bombs.py > src/bombs.c
"""

RAW = (
 "a0b2d1a2e1d0b2a0f1b2c1f0b0d2f1b2e1a0b2e0c1b0f1d2b2f1e0c2a1b0c1a0e2c0e2f1a1"
 "b0f2c3a2b3f0d1a1f3c2b0a2f1e3b0a0f2e3d1b1c0f3d2b1e0d2c3b1f0e2a3c0a3e1b2c1b2"
 "a0e3c3b2a1f0c0d2a1b3a0b1f4d2e3a1c0f3b4e2a1f4b0e3d2a4f2d1e3b0b2c0d3f4a1b0c4"
 "e2f1d3b3d0a2f1e4b2e0c4d3a1b"
 "3e2d4c1f0c3a1f2e4b0c1b4d2a0e3c2b4e1f3a0a1e3b5d4c0f2a1e5b4f2c3d0a3f4d1e5b2c"
 "0a3f1e0c2b4d5b3a2c5f4d1e0b2c0e3a1d5f4b4c1f3d2e0a5b2e0a5c4f1d3b5f1a2d3e0c4b"
 "4f0e3a1d2c5c3b0d4a2f5e1c5b3d1f2a4e0"
)

assert len(RAW) == 432, "expected 432 packed characters, got %d" % len(RAW)

MAX_WIRES = 6
GROUP_SIZES = [3, 4, 5, 6]
BOMBS_PER_GROUP = 12

bombs = []
pos = 0
for wires in GROUP_SIZES:
    for _ in range(BOMBS_PER_GROUP):
        colours = [0] * MAX_WIRES
        orders = [0] * MAX_WIRES
        for w in range(wires):
            letter = RAW[pos]
            digit = RAW[pos + 1]
            pos += 2
            colour = ord(letter) - ord('a')
            order = ord(digit) - ord('0')
            assert 0 <= colour <= 5, "bad colour letter %r" % letter
            assert 0 <= order <= 5, "bad order digit %r" % digit
            colours[w] = colour
            orders[w] = order
        bombs.append((wires, colours, orders))

assert pos == len(RAW), "did not consume the whole packed string (%d/%d)" % (pos, len(RAW))
assert len(bombs) == 48, "expected 48 bombs, got %d" % len(bombs)

# Sanity check: each bomb's non-zero orders form a permutation of 1..wires-1.
for i, (wires, colours, orders) in enumerate(bombs):
    used = sorted(o for o in orders[:wires] if o != 0)
    assert used == list(range(1, wires)), \
        "bomb %d has bad cut order sequence: %r" % (i, orders[:wires])

print("/*")
print(" * Generated by tools/gen_bombs.py from the packed Atari Bomb Squad")
print(" * bomb table. Do not edit by hand -- edit the generator instead.")
print(" */")
print()
print('#include "bombs.h"')
print()
print("const Bomb bombs[BOMB_COUNT] = {")
for wires, colours, orders in bombs:
    colstr = ", ".join(str(c) for c in colours)
    ordstr = ", ".join(str(o) for o in orders)
    print("    { %d, { %s }, { %s } }," % (wires, colstr, ordstr))
print("};")
